//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNotepad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapNotepad.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Pin.
        /// </summary>
        public static string AddPinTitle {
            get {
                return ResourceManager.GetString("AddPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work correctly app needs&apos; your location!.
        /// </summary>
        public static string AndroidLocationAlert {
            get {
                return ResourceManager.GetString("AndroidLocationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string BadEmailAlert {
            get {
                return ResourceManager.GetString("BadEmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one capital letter, one number, mus&apos;t contain spaces and be between 4 and 20 characters long!.
        /// </summary>
        public static string BadPasswordAlert {
            get {
                return ResourceManager.GetString("BadPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or email!.
        /// </summary>
        public static string BadPasswordEmailAlert {
            get {
                return ResourceManager.GetString("BadPasswordEmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 1 and 20 characters long!.
        /// </summary>
        public static string BadUserNameAlert {
            get {
                return ResourceManager.GetString("BadUserNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change search categories.
        /// </summary>
        public static string ChangeCategoriesLabel {
            get {
                return ResourceManager.GetString("ChangeCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string CPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ACCOUNT.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin description musn&apos;t contain | symbol !.
        /// </summary>
        public static string DescroptionAlert {
            get {
                return ResourceManager.GetString("DescroptionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccLabel {
            get {
                return ResourceManager.GetString("DontHaveAccLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pin.
        /// </summary>
        public static string EditPinTitle {
            get {
                return ResourceManager.GetString("EditPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here :(.
        /// </summary>
        public static string EmptyListLabel {
            get {
                return ResourceManager.GetString("EmptyListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is already taken!.
        /// </summary>
        public static string ExistEmailAlert {
            get {
                return ResourceManager.GetString("ExistEmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins&apos; name is already exist!.
        /// </summary>
        public static string ExistNameAlert {
            get {
                return ResourceManager.GetString("ExistNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string GymCategory {
            get {
                return ResourceManager.GetString("GymCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string HotelCategory {
            get {
                return ResourceManager.GetString("HotelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QR Code!.
        /// </summary>
        public static string InvalidQrAlert {
            get {
                return ResourceManager.GetString("InvalidQrAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work correctly app needs&apos; your location! Please, go to settings and enable it!.
        /// </summary>
        public static string IOSLocationAlert {
            get {
                return ResourceManager.GetString("IOSLocationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid latitude!.
        /// </summary>
        public static string LatitudeAlert {
            get {
                return ResourceManager.GetString("LatitudeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin latitude.
        /// </summary>
        public static string LatitudePlaceholder {
            get {
                return ResourceManager.GetString("LatitudePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG OUT.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid longitude!.
        /// </summary>
        public static string LongitudeAlert {
            get {
                return ResourceManager.GetString("LongitudeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin longitude.
        /// </summary>
        public static string LongitudePlaceholder {
            get {
                return ResourceManager.GetString("LongitudePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pin on map!.
        /// </summary>
        public static string MapAlert {
            get {
                return ResourceManager.GetString("MapAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP Notepad.
        /// </summary>
        public static string MapNotepanTitle {
            get {
                return ResourceManager.GetString("MapNotepanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NonCategory {
            get {
                return ResourceManager.GetString("NonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match!.
        /// </summary>
        public static string PasswordsNotMatchAlert {
            get {
                return ResourceManager.GetString("PasswordsNotMatchAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin category.
        /// </summary>
        public static string PinCategoryTitle {
            get {
                return ResourceManager.GetString("PinCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin name musn&apos;t be empty and musn&apos;t contain | symbol !.
        /// </summary>
        public static string PinNameAlert {
            get {
                return ResourceManager.GetString("PinNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin name.
        /// </summary>
        public static string PinNamePlaceholder {
            get {
                return ResourceManager.GetString("PinNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My pins.
        /// </summary>
        public static string PinsListTitle {
            get {
                return ResourceManager.GetString("PinsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point the camera at QR Code in another Map Notepad app.
        /// </summary>
        public static string QrScanHint {
            get {
                return ResourceManager.GetString("QrScanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning QR Code.
        /// </summary>
        public static string QrScanTitle {
            get {
                return ResourceManager.GetString("QrScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string RestaurantCategory {
            get {
                return ResourceManager.GetString("RestaurantCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin name is already exist! Change scaning pin name, or change exist pin name!.
        /// </summary>
        public static string ScanPinNameAlert {
            get {
                return ResourceManager.GetString("ScanPinNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareButton {
            get {
                return ResourceManager.GetString("ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket.
        /// </summary>
        public static string SupermarketCategory {
            get {
                return ResourceManager.GetString("SupermarketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin name or....
        /// </summary>
        public static string TextSearchBar {
            get {
                return ResourceManager.GetString("TextSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use map.
        /// </summary>
        public static string UseMapCheckbox {
            get {
                return ResourceManager.GetString("UseMapCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string UserLogoutAlert {
            get {
                return ResourceManager.GetString("UserLogoutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNamePlaceholder {
            get {
                return ResourceManager.GetString("UserNamePlaceholder", resourceCulture);
            }
        }
    }
}
